//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization; 

namespace ProductFinderService
{
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class Product
    {
        public Product()
        {
            this.Images = new HashSet<Image>();
            this.Reviews = new HashSet<Review>();
        }
    
    	[DataMember]
        public int Id { get; set; }
    	[DataMember]
        public string DisplayName { get; set; }
    	[DataMember]
        public System.DateTime RevisionDate { get; set; }
    	[DataMember]
        public string Title { get; set; }
    	[DataMember]
        public int ListOrderOverride { get; set; }
    	[DataMember]
        public string ShortDescription { get; set; }
    	[DataMember]
        public int IndustryId { get; set; }
    	[DataMember]
        public int CategoryId { get; set; }
    	[DataMember]
        public int BrandId { get; set; }
    
        public virtual ICollection<Image> Images { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual Category Category { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
